### ISSUE TITLE
Viết báo cáo (30-03-2016)

### ISSUE THREAD

**Issue by rinodung** [rinodung/sql-nosql-ci#13]
Mỗi thành viên chịu trách nhiệm viết phần của mình thành file word sau đó chị Hạnh sẽ tổng hợp lại, deadline 30-03-2016

**Comment by Dunghanh** [comment]
Ok
Vào 02-03-2016 19:18, "Dong Dung" notifications@github.com đã viết:

**Comment by xuanvinh26** [comment]
Cho hỏi là phần edit lại cái database có làm ko và làm như thế
nào vậy dũng, cấu trúc bảng như thế nào?

---

Trương Xuân Vinh
Cisco Academy Instructor, NetAcad Staff, ASC Academy Staff
ITP Training Center - Infomation Technology Park, VNU-HCM
Quarter 6, Linh Trung Ward, Thu Duc District, Ho Chi Minh City, Viet Nam
Email: vinh.truong@vnu-itp.edu.vn or xuanvinh.uit@gmail.com or t
09520355@gm.uit.edu.vnxvinh.it@gmail.com
Phone: 0947394971

Vào 20:07 Ngày 02 tháng 03 năm 2016, Dunghanh notifications@github.com đã
viết:

**Comment by rinodung** [comment]
vẫn giữ lại cơ sở dữ liệu cũ, vì mọi người cũng không có thời gian để làm. 

Mọi người nộp lại tập tin word trước ngày 24/03/2016 để chị @Dunghanh, @mickey123456  tổng hộp rồi nộp cho thầy (30-03-2016)nhé.

**Comment by rinodung** [comment]
Em gửi bài word MongoDB của em:
[Bao Cao CSDL Nang Cao.docx](https://github.com/rinodung/sql-nosql-ci/files/184386/Bao.Cao.CSDL.Nang.Cao.docx)

**Comment by xuanvinh26** [comment]
Cho e tối nay gửi nha, em bận nhiều việc quá chưa hoàn tất được.

---

Trương Xuân Vinh
Cisco Academy Instructor, NetAcad Staff, ASC Academy Staff
ITP Training Center - Infomation Technology Park, VNU-HCM
Quarter 6, Linh Trung Ward, Thu Duc District, Ho Chi Minh City, Viet Nam
Email: vinh.truong@vnu-itp.edu.vn or xuanvinh.uit@gmail.com or t
09520355@gm.uit.edu.vnxvinh.it@gmail.com
Phone: 0947394971

2016-03-22 22:23 GMT+07:00 Dong Dung notifications@github.com:

**Comment by xuanvinh26** [comment]
Hi all,

Em gửi báo cáo Cassandra.

https://drive.google.com/file/d/0B8Gg7y4Uuna2R01aVlJzRHJYSTA/view?usp=sharing

---

Trương Xuân Vinh
Cisco Academy Instructor, NetAcad Staff, ASC Academy Staff
ITP Training Center - Infomation Technology Park, VNU-HCM
Quarter 6, Linh Trung Ward, Thu Duc District, Ho Chi Minh City, Viet Nam
Email: vinh.truong@vnu-itp.edu.vn or xuanvinh.uit@gmail.com or t
09520355@gm.uit.edu.vnxvinh.it@gmail.com
Phone: 0947394971

2016-03-24 11:20 GMT+07:00 Vinh Xuân txvinh.it@gmail.com:

**Comment by phatnnt** [comment]
Hi all,

Em gửi báo cáo Redis.

https://drive.google.com/file/d/0Bw6oMcUTO7Uca2FhZnc3d212RWs/view

**Comment by xuanvinh26** [comment]
Hi all,

Nãy anh Phúng nói là gửi báo cáo file mềm cho anh Phúng, hok biết
hai chị có gửi cho anh chưa. :D

Thanks.

---

Trương Xuân Vinh
Cisco Academy Instructor, NetAcad Staff, ASC Academy Staff
ITP Training Center - Infomation Technology Park, VNU-HCM
Quarter 6, Linh Trung Ward, Thu Duc District, Ho Chi Minh City, Viet Nam
Email: vinh.truong@vnu-itp.edu.vn or xuanvinh.uit@gmail.com or t
09520355@gm.uit.edu.vnxvinh.it@gmail.com
Phone: 0947394971

2016-03-27 23:05 GMT+07:00 phatnnt notifications@github.com:

**Comment by mickey123456** [comment]
Nop roi em trai

On Mon, Apr 4, 2016 at 10:44 PM, xuanvinh26 notifications@github.com
wrote:

> Hi all,
> 
> Nãy anh Phúng nói là gửi báo cáo file mềm cho anh Phúng, hok biết
> hai chị có gửi cho anh chưa. :D
> 
> Thanks.
> 
> ---
> 
> Trương Xuân Vinh
> Cisco Academy Instructor, NetAcad Staff, ASC Academy Staff
> ITP Training Center - Infomation Technology Park, VNU-HCM
> Quarter 6, Linh Trung Ward, Thu Duc District, Ho Chi Minh City, Viet Nam
> Email: vinh.truong@vnu-itp.edu.vn or xuanvinh.uit@gmail.com or t
> 09520355@gm.uit.edu.vnxvinh.it@gmail.com
> Phone: 0947394971
> 
> 2016-03-27 23:05 GMT+07:00 phatnnt notifications@github.com:
> 
> > Closed #13 https://github.com/rinodung/sql-nosql-ci/issues/13.
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/rinodung/sql-nosql-ci/issues/13#event-604525898
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/rinodung/sql-nosql-ci/issues/13#issuecomment-205358388

## 

Tran Thi Thu Thuy
Mobile: 0909.714.699
